version: '3.8'

services:
  semcomm:
    build: .
    image: subash_semcomm:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./results:/workspace/results
      - ./checkpoints:/workspace/checkpoints
      - ./wandb:/workspace/wandb
    environment:
      - WANDB_MODE=offline
    command: python run_train.py
